# Generated by Django 3.0.6 on 2020-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(default=None)),
                ('player_dob', models.DateField(default=None)),
                ('player_country', models.TextField(default=None)),
                ('player_curr_team', models.TextField(default=None)),
                ('player_position', models.TextField(default=None)),
                ('player_photo', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(default=None)),
                ('stadium', models.TextField(default=None)),
                ('est_year', models.IntegerField(default=None)),
                ('curr_trainer', models.TextField(default=None)),
                ('UEFA_rate', models.IntegerField(default=None)),
                ('emblem', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
