# Generated by Django 3.0.6 on 2020-05-30 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_curr_team_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FootballApp1.Team'),
        ),
    ]
