# Generated by Django 3.0.6 on 2020-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp1', '0002_player_player_curr_team_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(default=None, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='team',
            name='emblem',
            field=models.ImageField(default=None, upload_to='gallery'),
        ),
    ]
