# Generated by Django 3.0.6 on 2020-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp1', '0003_auto_20200530_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_curr_team',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_position',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='curr_trainer',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
