# Generated by Django 3.0.6 on 2020-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp1', '0004_auto_20200531_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_country',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_curr_team',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_dob',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(default=None, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_position',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
