# Generated by Django 3.0.6 on 2020-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballApp1', '0005_auto_20200531_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='team',
            name='emblem',
            field=models.ImageField(blank=True, default=None, upload_to='gallery'),
        ),
    ]
